### ISSUE TITLE
JSON Conflict error with manually including JSON gem 

### ISSUE THREAD

**Issue by mikeyoungyoung** [contentful/contentful.rb#105]
I have an issue using the contactful.rb gem.  Error below:
`/Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2284:in`raise_if_conflicts': Unable to activate contentful-1.0.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
    from /Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1407:in `activate'
    from /Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb:196:in`rescue in try_activate'
    from /Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
    from /Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in`rescue in require'
    from /Users/michael.young/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from app.rb:7:in`<main>'`

When I try and pull back content through irb it runs fine, but in my sinatra app where I have also manually included json I see the above error

**Comment by dlitvakb** [comment]
Hey @mikeyoungyoung,

Sadly the fixed `json` dependency is in order to support older versions of Ruby.

We're considering removing this dependency and deprecating Ruby versions < 2.0 soon, but sadly this is not currently possible.

I'd recommend you to for the moment create a fork without this hard dependency and use it from there or use a local copy of the gem with the `json` dependency removed.

Hope this helps, and hope we can get this solved on the mainstream release soon.

Cheers

**Comment by dlitvakb** [comment]
Hwy @mikeyoungyoung,

#106 removes the hard dependency on `json`.

Hope that helps

Cheers

**Comment by mikeyoungyoung** [comment]
perfect! works for me

**Comment by dlitvakb** [comment]
@mikeyoungyoung we will be releasing today, only a very small refactor pending after review 😄

**Comment by dlitvakb** [comment]
@mikeyoungyoung `1.0.1` has been released 😄 

Cheers

**Comment by rohanschari** [comment]
After executing calabash-android run test.apk

Unable to activate calabash-android-0.9.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1408:in `activate'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/home/apmosys/VED/CreditCardValidator.AndroidStudio/SimpleCreditCardValidator/features/support/env.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/usr/local/rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.0/bin/cucumber:22:in `load'
/usr/local/rvm/gems/ruby-2.4.0/bin/cucumber:22:in `<main>'

**Comment by dlitvakb** [comment]
Hey @rohanschari,

Looks like your issue is with either `cucumber` or some other gem, there's no hard requirement on the `json` gem any more.

Either update to a newer version or make sure that there's no other conflicting gem in your project.

Cheers
