### ISSUE TITLE
Infinite loop / stuck process printing response to stdout / console

### ISSUE THREAD

**Issue by steakchaser** [contentful/contentful.rb#124]
Hi.  We have a content structure that contains possible circular references.  i.e. Entry 1 -> related entries -> Entry 2 -> related entries -> Entry 1

In the API call, we are specifying an `include = 3`, so technically this circular referencing should be terminated after 3 levels deep.  The API call works fine and we can parse the response fine in code.  BUT, if you attempt to `puts` the response object `client.entries` to the console, it hangs.

Any thoughts?

**Comment by dlitvakb** [comment]
Hey @steakchaser,

Which version of the SDK are you using? If using master, please update to the latest version of master, and reduce the client configuration parameter `max_include_resolution_depth` to a value equal or greater than your maximum `include` level. This will avoid resolving circular references for a long time. 

The current default level is 20, and if you have circular references, on just 2 entries, this process can take up to 6 seconds, if the circularity is more complex, the time grows exponentially, and that's why you seem to notice the process being "stuck". I did a benchmark with 30 entries all pointing to each other with the default value, and took over 6 minute on a 2015 MacBook Pro with all maxed out specs to finish resolving the tree. When changed the default value to 5, thus limiting greatly the size of the resolution tree, the resolution took less than 3 seconds on average.

This only occurs when having circular references, on any other case, the value of 20 as a default is a completely sane default, which allows elements on the max API-level include (`10`) to have back references and have the SDK properly resolve them. Having no performance issues in several load tests.

If you are using a lower include level (but have circular references), feel free to reduce it to a number that makes sense to you, and this will drastically improve performance.

Cheers

**Comment by steakchaser** [comment]
@dlitvakb Thanks for that!  Works great.  Definitely looking forward to this being in the next release.  Nice work.

**Comment by dlitvakb** [comment]
This has now been released.

Cheers!
