### ISSUE TITLE
Breaking change with snakified IDs

### ISSUE THREAD

**Issue by felixjung** [contentful/contentful.rb#134]
Hey @dlitvakb, when trying your fix in #133 I noticed that our build is still broken. While pulling content using the Jekyll plugin now works, it seems that all IDs are now snake-cased rather than camel-cased.

This breaks our entire front-end as our templating relies on the IDs to be the same as in the API.

Is this done so on purpose? I find it quite counter-intuitive that the API behaves different than the client libraries.

**Comment by felixjung** [comment]
PS: I could not find this in the [list of breaking changes](https://github.com/contentful/contentful.rb/blob/master/CHANGELOG.md#200) for 2.0 😉

**Comment by dlitvakb** [comment]
Hey @felixjung,

This is by design, looks like I forgot to add it to the list, all properties now match accessors.

It makes mapping way easier to maintain, before there were 2 separate places in which properties were stored `@properties` and `@fields` and there was a correlation between those required in order to keep the original ID. Now by making sure that the internal representation and the accessor match, makes it way easier to then resolve them.

I'm extremely sorry that this broke your build, it's a really bad oversight on my part.

I'll add the clarification in the CHANGELOG both here and in the Jekyll Integration.

Once again, sorry for this.

Cheers

**Comment by felixjung** [comment]
Thanks 👍

**Comment by dlitvakb** [comment]
Done 😄
