### ISSUE TITLE
Draft entries returned by Content Delivery API

### ISSUE THREAD

**Issue by damireh** [contentful/contentful.rb#177]
I have an entry that references other entries but the API is returning the draft referenced entries as part of the response; and I was under the impression it would only return published entries unless you use the preview api/token?

<img width="779" alt="screenshot 2018-08-14 23 08 45" src="https://user-images.githubusercontent.com/429845/44118611-0507cdca-a017-11e8-86fb-b2c6be9d2610.png">

In the example above this is the response im receiving from the API

```ruby
> content.experts
[<Contentful::Link id='3rwmNyX132m4A0gqWCu2go'>, <Contentful::Link id='3qkA1aMIruQaICu4EUioiM'>, <Contentful::Link id='5FZjRIRlio8ISI4Iq00IAs'>]

> content.experts.map(&:raw)
[{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"3rwmNyX132m4A0gqWCu2go"}},
 {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"3qkA1aMIruQaICu4EUioiM"}},
 {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"5FZjRIRlio8ISI4Iq00IAs"}}]
```

While its not actually returning the content of the draft entries; its still returning their IDs, is this expected?

**Comment by dlitvakb** [comment]
Hi @damireh.

Which version of the SDK are you using?

Cheers

**Comment by damireh** [comment]
contentful (2.8.0)

**Comment by dlitvakb** [comment]
Can you share how you're instantiating the client?

Cheers

**Comment by damireh** [comment]
```ruby
Contentful::Client.new(
  space: "xx",
  environment: "xxx",
  dynamic_entries: :auto,
  access_token: "xxx"
)
```

And im fetching the entries like so

```ruby
client.entries(content_type: :page, include: 3,  "fields.slug" => slug).first
```

**Comment by dlitvakb** [comment]
Hey @damireh,

Could you create a support request in https://support.contentful.com and request for my help?

I'll need you to send your access token, space ID and environment ID so that I can test this properly.

As this issue shouldn't be happening since the release of version 2.5.0.

Cheers

**Comment by damireh** [comment]
Will do 👍 Thank you

**Comment by MatteoGioioso** [comment]
Did you manage to find the problem? I have the exact same issue

**Comment by rubydog** [comment]
Hey @MatteoGioioso, thanks for reporting the issue.   I am looking into it. I will get back to you if I need more details.

Cheers

**Comment by roelkok** [comment]
I'm having the same issue two years later.

**Comment by ethan-ozelius-contentful** [comment]
I know this issue from 2018, but for posterity,

The API and this SDK [returning draft entities is expected behavior](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/entries/unresolved-entries).  This will not be changed at the API level because that would constitute a breaking change.

workaround: check response.errors array for unresolved links.

However, the default behavior of the ruby SDK is to omit "unresolved" (in this case draft) linked entries.

If I have an entry like this, where I have 2 referenced entries, only one of which is published, I will only get the published one.

<img width="1288" height="704" alt="Image" src="https://github.com/user-attachments/assets/1cc61079-d22a-4850-924f-f49066547872" />

```ruby
entry = client.entry('3UwcllO079Q7hgu73tbNeX', include: 2)

puts "Entry: #{entry.id} (#{entry.content_type.id})"
puts JSON.pretty_generate(entry.fields)

# output:
# Entry: 3UwcllO079Q7hgu73tbNeX (rubyGithubIssue177)
# {
#   "title": "asdf",
#   "references": [
#     "#<Contentful::Entry:0x000000012242e4d8>"
#   ]
# }
```
