### ISSUE TITLE
A way to expose Contentful request IDs in ServiceUnavailable errors

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful.rb#185]
Contentful support has requested that we provide request IDs for spurious 503 errors we are receiving from the Contentful Content Delivery API, but contentful.rb does not appear to expose this information in the event of a ServiceUnavailable error being thrown. 

Is there a way to obtain the request ID from a Contentful::ServiceUnavailable error? If not, could this be added?

Of course, our logs clearly delineate when we deliver 500 errors to our clients, so it's surprising Contentful cannot seem to locate these errors in it's own logs.

**Comment by dlitvakb** [comment]
Hey @rezonant,

Request IDs are always included for all error messages.

Cheers

**Comment by rezonant** [comment]
Request IDs are not shown in the error message itself in my experience @dlitvakb -- Contentful support advised us to do this to access the requestId:

> If you rescue that exception then you can retrieve the request ID from the response headers like this:

`error.response.load_json.fetch('requestId', 'unknown')`

> Alternatively also:

`error.response.headers['x-contentful-request-Id']`

**Comment by dlitvakb** [comment]
Hey @rezonant,

I've forwarded those snippets to the support team.

That said, they should not be required at all, unless the 500 is not coming from Contentful itself but because there was a failure in the delivery pipeline, like the CDN failing, or something alike, in which case the response you'd be getting wouldn't be coming from Contentful directly, as our API responses always contain the `requestID` as part of the body of the response (what you're getting with the first of the 2 snippets), which is what the error formatting code uses to print out the `requestID` on the formatted errors.

Hope this explains it better,

Cheers
