### ISSUE TITLE
(Version 2.11.0) ContentfulModel#try(:optional_field) raises Contentful::EmptyFieldError

### ISSUE THREAD

**Issue by keithm-thompson** [contentful/contentful.rb#193]
Hello,

As the title suggests, the change in version 2.11.0 to raise on calls to empty fields causes `Object#try` to behave in a non-intuitive way. Removing the definition of `respond_to_missing?` [here]( https://github.com/contentful/contentful.rb/blob/cd0edb0e2cebc2176d231fe66c9a602b879d06ff/lib/contentful/entry.rb#L100) retains the behavior that you were looking to add in that patch (as `ContentfulModel.optional_field` would still throw an error) but allows the gem to continue to be in line with Ruby's standards. 

I'm happy to submit a PR if you agree that `Object#try` shouldn't throw an error for Contentful Entries.

Thanks 🙂

**Comment by dlitvakb** [comment]
Hey @keithm-thompson,

Using `Object#try` from `ActiveSupport` is often considered a smell, you can read a more informed explanation about it here: https://karolgalanciak.com/blog/2017/09/24/do-or-do-not-there-is-no-try-object-number-try-considered-harmful/

In any case, if you rely on `#try`, you can change the `:raise_for_empty_field` configuration parameter to `false`.

If that doesn't work for you, I can look into options for customising this behaviour a bit more, to change the exception thrown to `NoMethodError`, or anything else that you may want.

Still, I do believe that the new behaviour is the correct behaviour for this SDK, but we can work on adding a bit more flexibility, so that your use-case is also possible.

Cheers

**Comment by keithm-thompson** [comment]
Hey @dlitvakb,

I tend to agree that `Object#try` should be avoided in most cases. Unfortunately, this is a case in which there are existing calls in the code base to `Object#try` and updating the Gem broke those calls. 

I was hoping to avoid changing that config to false since I am a fan of the new behavior 🙂. 

My suggestion to remove the overriding of `respond_to_missing?` was due to the [implementation](https://github.com/rails/rails/blob/5-2-0/activesupport/lib/active_support/core_ext/object/try.rb#L8) in ActiveSupport. It rely's on the object's `respond_to?` method.

At worst, I'd be happy to make some adjustments locally to support my use-case. I thought you should be aware if you weren't 😄 

Thanks!

**Comment by dlitvakb** [comment]
Hey @keithm-thompson,

I'm glad that you like the change.

That said, I'm super confused onto what the best approach to solve this is.

If I remove the `#respond_to_missing?` implementation, it would mean to keep exact backwards compatibility, but actually produce incorrect behaviour, as the field should *actually* have an accessible method in the entry object, even if it's empty. Because the correct check should be done against `entry.fields.key?(:optional_field)`.

Maybe I can update the `#respond_to_missing?` code to do the following:

```ruby
def respond_to_missing?(name, include_private = false)
  (content_type_field?(name) && fields.key?(name)) || super
end
```

With this snippet it would be backwards compatible, but I think that it leads to feature creep.

WDYT?

Cheers

**Comment by keithm-thompson** [comment]
Hey @dlitvakb,

Ah, I see. I misunderstood your intentions with the change. My apologies.

> as the field should _actually_ have an accessible method in the entry object,  even if it's empty.

With this intended behavior, I think the current implementation works as it should. To state my understanding of the objective slightly differently, you want entries to operate as if there were methods defined on them like so:
```ruby
def optional_field
  raise Contentful::EmptyFieldError
end
```
In which case, calling `#try(:optional_field)` would result in an error.

With this in mind, as long as you're fine with not keeping backwards compatibility, I wouldn't suggest any changes. As a stop-gap, we can handle our use-case by ensuring the key exists in the fields hash and then come up with a more elegant solution for the longer term.

Thanks!

**Comment by dlitvakb** [comment]
Hey @keithm-thompson,

Thanks for understanding, that said, you can disable `:raise_for_empty_field` and keep using `#try` as it would return the `NilClass#try` chainable.

Cheers
