### ISSUE TITLE
Contentful::Asset#to_json raises 'stack level too deep' error

### ISSUE THREAD

**Issue by elyngved** [contentful/contentful.rb#201]
I'm trying to consume a rich text field which comes in a nested node format. Calling `to_json` on this hash and then passing to [rich-text-html-renderer](https://github.com/contentful/rich-text/tree/master/packages/rich-text-html-renderer) worked well, until we tried including images in the body.

Calling `to_json` or `as_json` on a `Contentful::Asset` object raises a `SystemStackError: stack level too deep` error.

Is there a known fix or workaround?

**Comment by dlitvakb** [comment]
Hey @elyngved,

Any reason why you're using the JS rich text library, instead of the Ruby version?

If you're still going to be using the JS library, then please use `asset.raw` instead, this returns the JSON returned from the API.

While `#to_json` without overwriting it returns the calculated JSON of the object, which if you're in a Rails application, conflicts with some serialization of ActiveSupport, which leads to these `SystemStackError` exceptions.

Hope this helps,

Cheers

**Comment by elyngved** [comment]
Only because I didn't find it on my own! For anyone else reading, check out this official Ruby rich text gem: https://github.com/contentful/rich-text-renderer.rb

**Comment by elyngved** [comment]
In case you're wondering, this is the workaround I found.. I didn't investigate any farther than this :)

```rb
class Contentful::Asset
  alias_method :to_hash, :raw
end
```

**Comment by dlitvakb** [comment]
Glad you were able to find the library, and solve your issue.

Is it alright if we close this issue?

Cheers
