### ISSUE TITLE
Retrieving all entries crashes with NoMethodError: undefined method `key?' for <Contentful::Link id='icon'>:Contentful::Link

### ISSUE THREAD

**Issue by seanbourkemckenna** [contentful/contentful.rb#244]
Just installed the Contentful ruby gem and I'm running into this error when trying to do a basic fetch of all entries from a space. 

Similar to what you have in the docs 

```
entries = client.entries

entries.each do |entry|
  if entry.fields[:productName]
    puts entry.fields[:productName]
  end
end
```

```
NoMethodError: undefined method `key?' for <Contentful::Link id='icon'>:Contentful::Link
from /home/sean.bourkemckenna/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/contentful-2.16.2/lib/contentful/base_resource.rb:12:in `initialize'
```

Which points to here 

https://github.com/contentful/contentful.rb/blob/master/lib/contentful/base_resource.rb#L12

How can I unblock this?

**Comment by GabrielAnca** [comment]
Hi team 👋🏻 Sean and I have been doing some debugging on this and would like to share some extra feedback.

As you can see above, the issue is that the library is expecting to get a Hash on the constructor, but it's getting a `Contentful::Link` object.

We've added a breakpoint on the `hydrate_metadata` method when building the tags:

![image](https://user-images.githubusercontent.com/251391/149811731-84f798bc-e050-4fa0-9e28-63a4f8a308ab.png)

This shows 

```

**Comment by GabrielAnca** [comment]
Hi team 👋🏻 Sean and I have been doing some debugging on this and would like to share some extra feedback.

As you can see above, the issue is that the library is expecting to get a Hash on the constructor, but it's getting a `Contentful::Link` object.

We've added a breakpoint on the `hydrate_metadata` method when building the tags:

![image](https://user-images.githubusercontent.com/251391/149811731-84f798bc-e050-4fa0-9e28-63a4f8a308ab.png)

At that point, `raw['metadata']['tags']` has an array of objects rather than an array of Hashes:

```ruby
[1] pry(#<Contentful::Asset>)> raw
=> {"metadata"=>{"tags"=>[<Contentful::Link id='icon'>]},
 "sys"=>
  {"space"=>{"sys"=>{"type"=>"Link", "linkType"=>"Space", "id"=>"xxxxxxxxxxxxxxxxxxxxxxx"}},
   "id"=>"xxxxxxxxxxxxxxxxxxxxxxx",
   "type"=>"Asset",
   "createdAt"=>"2021-06-14T18:52:40.328Z",
   "updatedAt"=>"2021-12-08T15:59:39.052Z",
   "environment"=>{"sys"=>{"id"=>"master", "type"=>"Link", "linkType"=>"Environment"}},
   "revision"=>7,
   "locale"=>"en-US"},
 "fields"=>
...
```

It doesn't happen in all entries, so this seems limited to the entries that have tags.

Removing the tags from the assets in Contentful fixes the issue. It looks like at some point when the item is built it's being stored in the metadata too 🤔

**Comment by rubydog** [comment]
Hi @GabrielAnca and @seanbourkemckenna 

Thanks for reporting the issue, I see the same error when trying to query entries. I will take a closer look at the issue here.

Will keep you posted.

Cheers
